boardgame_project:
  outputs:
    dev:
      account: jsa18243
      database: BOARDGAME
      password: "{{ env_var('DBT_PASSWORD') }}"
      role: transform
      schema: dbt_fbalseiro
      threads: 4
      type: snowflake
      user: "{{ env_var('DBT_USER') }}"
      warehouse: DBT_CERTIFICATION_PROJECT_WH
    ci:
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      database: "{{ env_var('SNOWFLAKE_DATABASE') }}"
      password: "{{ env_var('DBT_PASSWORD') }}"
      role: "{{ env_var('SNOWFLAKE_ROLE') }}"
      schema: dbt_ci
      threads: 4
      type: snowflake
      user: "{{ env_var('DBT_USER') }}"
      warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE') }}"
    prod:
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      database: "{{ env_var('SNOWFLAKE_DATABASE') }}"
      password: "{{ env_var('DBT_PASSWORD') }}"
      role: "{{ env_var('SNOWFLAKE_ROLE') }}"
      schema: dbt_prod
      threads: 4
      type: snowflake
      user: "{{ env_var('DBT_USER') }}"
      warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE') }}"
  target: prod
